# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from time import sleep
import random

a = random.randint(1, 90)
lst = []
speed = 2
for _ in range(90):
    n = 0
    while a in lst:
        a = random.randint(1,90)
    print(a)
    lst.append(a)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setEnabled(True)
        self.Title.setGeometry(QtCore.QRect(162, 20, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Title.setFont(font)
        self.Title.setMouseTracking(True)
        self.Title.setAutoFillBackground(True)
        self.Title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.Title.setObjectName("Title")
        self.Speed = QtWidgets.QLabel(self.centralwidget)
        self.Speed.setGeometry(QtCore.QRect(360, 150, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(30)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Speed.setFont(font)
        self.Speed.setObjectName("Speed")
        self.InputSpeed = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.InputSpeed.setGeometry(QtCore.QRect(500, 170, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.InputSpeed.setFont(font)
        self.InputSpeed.setObjectName("InputSpeed")
        self.Play = QtWidgets.QPushButton(self.centralwidget)
        self.Play.setGeometry(QtCore.QRect(190, 150, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.Play.setFont(font)
        self.Play.setObjectName("Play")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(190, 200, 141, 41))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(25)
        self.Stop.setFont(font)
        self.Stop.setObjectName("Stop")
        self.Credits = QtWidgets.QLabel(self.centralwidget)
        self.Credits.setGeometry(QtCore.QRect(490, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Credits.setFont(font)
        self.Credits.setObjectName("Credits")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(170, 110, 281, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Num = QtWidgets.QLabel(self.centralwidget)
        self.Num.setGeometry(QtCore.QRect(30, 150, 111, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Num.setFont(font)
        self.Num.setAlignment(QtCore.Qt.AlignCenter)
        self.Num.setObjectName("Num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.paused = False
        self.Play.clicked.connect(self.rand)
        self.InputSpeed.valueChanged.connect(self.valchange)
        self.sped = 2
    def rand(self, event):
        for i in lst:
            if not self.paused:
                self.Num.setText(str(i))
                app.processEvents()
                sleep(self.sped)
                self.Play.clicked.connect(self.pauser)
            else:
                while True:
                    if not self.paused:
                        break
    def pauser(self):
        self.paused = True
    def speeed(self):
        self.sped = 1
    def valchange(self):
        self.sped = self.InputSpeed.value() 
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tambola"))
        self.Title.setText(_translate("MainWindow", "Tambola"))
        self.Speed.setText(_translate("MainWindow", "Speed:"))
        self.Play.setText(_translate("MainWindow", "Play/Pause"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.Credits.setText(_translate("MainWindow", "Made by: Esh"))
        self.Num.setText('00')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
